behaviors:
  Reacher:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 102400
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.2
      lambd: 0.992
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 20
    max_steps: 60000000
    time_horizon: 1000
    summary_freq: 50000
    threaded: true

environment_parameters:
  QuickMovementScalar: 6
  AddNextTargetInfo: 1 # true
  TimeDecay: 0.992
  MinReward: 0.7
  torqueForce: 50
  MovePenalty: -0.001
